import PolicyPage from '../components/PolicyPage';

export default function TermsAndConditions() {
  return (
    <PolicyPage
      title="Terms and Conditions"
      summary="These terms govern your access to and use of the Hunger Hunt Parent website, mobile application, goods, and services."
    >
      <section>
        <h2>1. About these terms</h2>
        <p>
          This document is an electronic record under the Information Technology Act, 2000 and
          applicable rules concerning electronic records. It is generated by a computer system and
          does not require a physical or digital signature.
        </p>
        <p>
          The Hunger Hunt Parent platform at
          {' '}<a href="https://hunger-hunt-parent.vercel.app/">hunger-hunt-parent.vercel.app</a>,
          including its related mobile application, is owned by GRAARR MANAGEMENT SERVICES PRIVATE
          LIMITED (“HungerHunt”), whose registered office is at 120/3-M-I-S, Sainath Nagar, Revenue
          Ward No. 120, Kurnool, Andhra Pradesh, India - 518003.
          In these terms, HungerHunt is referred to as “we”, “us”, “our”, or the “Platform Owner”.
        </p>
      </section>

      <section>
        <h2>2. Acceptance and updates</h2>
        <p>
          By accessing, browsing, or using the platform, you agree to these Terms and Conditions and
          the policies incorporated into them by reference. If you transact through the platform,
          the policies applicable to that transaction also form part of your agreement with us. If you
          do not agree, do not use the platform.
        </p>
        <p>
          We may update these terms from time to time. You are responsible for reviewing them
          periodically to remain informed of changes.
        </p>
      </section>

      <section>
        <h2>3. Your account and information</h2>
        <p>
          To access and use the services, you agree to provide true, accurate, and complete information
          during and after registration. You are responsible for activity carried out through your
          registered account and for protecting its credentials.
        </p>
      </section>

      <section>
        <h2>4. Platform information and availability</h2>
        <p>
          Neither we nor third parties guarantee that information and materials offered through the
          platform will always be accurate, timely, complete, suitable, or uninterrupted. Information
          may contain inaccuracies or errors. To the fullest extent permitted by law, your use of the
          platform and services is at your own discretion, and you are responsible for assessing whether
          a service meets your requirements.
        </p>
      </section>

      <section>
        <h2>5. Intellectual property</h2>
        <p>
          Platform content, including its design, layout, appearance, text, and graphics, is owned by or
          licensed to HungerHunt. Using the platform does not transfer to you any intellectual-property
          right, title, or interest in that content. Unauthorised use may result in action under these
          terms or applicable law.
        </p>
      </section>

      <section>
        <h2>6. Payments and transactions</h2>
        <p>
          You agree to pay charges associated with the goods or services you request. When you initiate
          a transaction through the platform, you enter into a legally binding and enforceable contract
          with the Platform Owner for that transaction, subject to the applicable refund, cancellation,
          privacy, and shipping policies.
        </p>
      </section>

      <section>
        <h2>7. Acceptable use</h2>
        <p>
          You must not use the platform or services for any purpose that is unlawful, illegal, forbidden
          by these terms, or contrary to applicable Indian or local law. Links to third-party websites
          may be provided for convenience. When following them, you are governed by the third party&apos;s
          terms and privacy practices.
        </p>
      </section>

      <section>
        <h2>8. Indemnity</h2>
        <p>
          To the extent permitted by law, you agree to indemnify and hold harmless HungerHunt, its
          affiliates, officers, directors, agents, and employees from claims, demands, reasonable legal
          fees, or penalties arising from your breach of these terms or other platform policies, your
          violation of law, or your infringement of a third party&apos;s rights.
        </p>
      </section>

      <section>
        <h2>9. Force majeure</h2>
        <p>
          A party will not be liable for failing to perform an obligation under these terms where
          performance is prevented or delayed by an event beyond its reasonable control.
        </p>
      </section>

      <section>
        <h2>10. Governing law and disputes</h2>
        <p>
          These terms, and disputes concerning them or their enforceability, are governed by the laws
          of India. Disputes will be subject to the jurisdiction of the competent courts under applicable
          law.
        </p>
      </section>

      <section>
        <h2>11. Contact</h2>
        <p>
          Questions or communications concerning these terms may be sent to GRAARR MANAGEMENT
          SERVICES PRIVATE LIMITED (HungerHunt) by email at{' '}
          <a href="mailto:dhruv.kamma04@gmail.com">dhruv.kamma04@gmail.com</a>, or by post at
          120/3-M-I-S, Sainath Nagar, Revenue Ward No. 120, Kurnool, Andhra Pradesh, India - 518003.
          Support is available Monday to Friday, 9:00 to 18:00.
        </p>
      </section>
    </PolicyPage>
  );
}
